import { notFound } from "next/navigation";
import Link from "next/link";
import CTASection from "@/components/CTASection";
import JsonLd from "@/components/SEO/JsonLd";
import { getService, services } from "@/lib/services-data";
import { productCategories } from "@/lib/products-data";
import { createMetadata } from "@/lib/seo";
import { siteConfig } from "@/lib/site";

export const dynamicParams=false;
export function generateStaticParams(){return services.map(service=>({slug:service.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params; const service=getService(slug); if(!service)return {};
 return createMetadata({title:service.seoTitle,description:`${service.seoKeyword} for businesses, industries and institutions in Haryana, Delhi NCR and across India. Contact Corefix Technologies for a project consultation.`,path:`/services/${service.slug}`,keywords:service.seoKeywords});
}
export default async function ServicePage({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params; const service=getService(slug); if(!service)notFound();
 const relatedServices=services.filter(x=>x.slug!==service.slug).slice(0,3);
 const relatedProducts=productCategories.filter(p=>service.slug.includes("cctv")?p.slug==="cctv-security":service.slug.includes("dashcam")?p.slug==="dashcams-car-cameras":service.slug.includes("network")?p.slug==="networking":service.slug.includes("fencing")?p.slug==="perimeter-security":service.slug.includes("pa-")?p.slug==="pa-systems":service.slug.includes("fire")?p.slug==="fire-alarm-systems":service.slug.includes("classroom")?p.slug==="smart-classroom":service.slug.includes("conference")?p.slug==="conference-room-av":false);
 const breadcrumb={"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,name:"Home",item:siteConfig.url},{"@type":"ListItem","position":2,name:"Services",item:`${siteConfig.url}/services`},{"@type":"ListItem","position":3,name:service.title,item:`${siteConfig.url}/services/${service.slug}`}]};
 const serviceSchema={"@context":"https://schema.org","@type":"Service",name:service.title,description:service.description,serviceType:service.title,provider:{"@type":"Organization",name:siteConfig.name,url:siteConfig.url},areaServed:siteConfig.areasServed};
 const faqSchema={"@context":"https://schema.org","@type":"FAQPage",mainEntity:service.faqs.map(f=>({"@type":"Question",name:f.question,acceptedAnswer:{"@type":"Answer",text:f.answer}}))};
 const keywordText=service.seoKeywords.slice(0,8).join(", ");
 return <>
  <JsonLd data={breadcrumb}/><JsonLd data={serviceSchema}/><JsonLd data={faqSchema}/>
  <section className="bg-core-950"><div className="mx-auto max-w-7xl px-3 py-14 sm:px-4 sm:py-20 lg:px-8"><div className="max-w-4xl"><Link href="/services" className="text-xs font-bold text-yellow-400 sm:text-sm">← All Services</Link><div className="mt-6 flex h-11 w-11 items-center justify-center border border-yellow-400/40 bg-yellow-400/10 text-[10px] font-black text-yellow-400 sm:h-14 sm:w-14 sm:text-xs">{service.icon}</div><h1 className="mt-5 text-3xl font-black leading-tight text-white sm:text-4xl md:text-5xl lg:text-6xl">{service.title}</h1><p className="mt-5 max-w-3xl text-sm leading-6 text-white/65 sm:text-base sm:leading-7 lg:text-lg lg:leading-8">{service.description}</p></div></div></section>
  <section className="bg-black"><div className="mx-auto max-w-7xl px-3 py-12 sm:px-4 sm:py-20 lg:px-8"><div className="max-w-4xl space-y-5 text-sm leading-7 text-white/65 sm:text-base sm:leading-8"><h2 className="text-2xl font-black text-white sm:text-3xl">Professional {service.seoKeyword} for Project Requirements</h2><p>Corefix Technologies LLP provides {service.title.toLowerCase()} for {service.focus}. The solution is planned around the actual site, operating environment and project objective rather than a generic package. For organizations searching for {service.seoKeyword.toLowerCase()} in Haryana, Delhi NCR or across India, the focus is dependable infrastructure, correct equipment selection, professional installation and practical integration with the systems already used at the site.</p><p>A typical {service.seoKeyword.toLowerCase()} project can begin with a site survey, requirement analysis and technical planning. Corefix can coordinate product selection, cabling or mounting requirements, equipment configuration, testing, documentation and handover. Where the project includes connected technologies, the service can be integrated with CCTV, networking, audio-visual systems, alarms or other infrastructure. This is especially useful for factories, offices, educational campuses, warehouses and institutions where several systems need to operate together.</p><p>Clients can approach Corefix for new installations, system upgrades, expansion work, project supply and integrated deployments. The exact equipment depends on capacity, environment, site layout, operating conditions and technical specifications. Relevant terms from the supplied keyword research include {keywordText}. These phrases represent different search intents, so they are used naturally rather than repeated unnaturally.</p></div></div></section>
  <section className="bg-core-950"><div className="mx-auto grid max-w-7xl gap-8 px-3 py-12 sm:px-4 sm:py-20 lg:grid-cols-2 lg:gap-12 lg:px-8"><div><p className="text-xs font-black uppercase tracking-[.18em] text-yellow-400 sm:text-sm">Benefits</p><h2 className="mt-2 text-2xl font-black sm:text-3xl">What the solution delivers</h2><div className="mt-6 space-y-2.5 sm:space-y-3">{service.benefits.map(b=><div key={b} className="border border-white/10 bg-white/[.03] p-3 text-sm text-white/75 sm:p-4">✓ {b}</div>)}</div></div><div><p className="text-xs font-black uppercase tracking-[.18em] text-yellow-400 sm:text-sm">Implementation</p><h2 className="mt-2 text-2xl font-black sm:text-3xl">How Corefix handles the project</h2><ol className="mt-6 space-y-3 sm:space-y-4">{service.process.map((step,i)=><li key={step} className="flex gap-3 border-b border-white/10 pb-4"><span className="font-black text-yellow-400">0{i+1}</span><span className="text-sm leading-6 text-white/65 sm:text-base sm:leading-7">{step}</span></li>)}</ol></div></div></section>
  <section className="bg-black"><div className="mx-auto max-w-7xl px-3 py-12 sm:px-4 sm:py-20 lg:px-8"><p className="text-xs font-black uppercase tracking-[.18em] text-yellow-400 sm:text-sm">Industries Served</p><h2 className="mt-2 text-2xl font-black sm:text-3xl">Built for different operating environments</h2><div className="mt-6 flex flex-wrap gap-2">{service.industries.map(x=><span key={x} className="border border-white/10 px-3 py-2 text-xs text-white/70 sm:px-5 sm:py-3 sm:text-sm">{x}</span>)}</div></div></section>
  <section className="bg-core-950"><div className="mx-auto max-w-7xl px-3 py-12 sm:px-4 sm:py-20 lg:px-8"><h2 className="text-2xl font-black sm:text-3xl">Frequently Asked Questions</h2><div className="mt-6 grid gap-3 md:grid-cols-2">{service.faqs.map(f=><details key={f.question} className="border border-white/10 bg-white/[.03] p-4"><summary className="cursor-pointer text-sm font-bold text-white">{f.question}</summary><p className="mt-3 text-sm leading-6 text-white/60">{f.answer}</p></details>)}</div></div></section>
  <section className="bg-black"><div className="mx-auto max-w-7xl px-3 py-12 sm:px-4 sm:py-20 lg:px-8"><h2 className="text-2xl font-black sm:text-3xl">Related Corefix Solutions</h2><div className="mt-6 grid gap-3 md:grid-cols-3">{relatedServices.map(item=><Link key={item.slug} href={`/services/${item.slug}`} className="border border-white/10 p-4 text-sm font-bold text-white hover:border-yellow-400 hover:text-yellow-400">{item.title} →</Link>)}</div>{relatedProducts.length>0&&<><h3 className="mt-10 text-xl font-black">Related Products</h3><div className="mt-4 flex flex-wrap gap-2">{relatedProducts.map(p=><Link key={p.slug} href={`/products/${p.slug}`} className="border border-yellow-400/30 px-4 py-2 text-sm text-yellow-400">{p.name} →</Link>)}</div></>}</div></section>
  <CTASection/>
 </>;
}
