import Link from "next/link";
import Hero from "@/components/Hero";
import CTASection from "@/components/CTASection";
import JsonLd from "@/components/SEO/JsonLd";
import { productCategories } from "@/lib/products-data";
import { createMetadata } from "@/lib/seo";
import { siteConfig } from "@/lib/site";
export const metadata=createMetadata({title:"Security & IT Products in Haryana | Corefix Technologies",description:"Explore CCTV, dashcams, networking, fencing, PA, fire alarm, smart classroom and conference AV products for projects across India.",path:"/products",keywords:["CCTV products","dashcam products","networking equipment","fire alarm systems","PA systems","smart classroom equipment","Haryana","Pan-India"]});
export default function ProductsPage(){const breadcrumb={"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,name:"Home",item:siteConfig.url},{"@type":"ListItem","position":2,name:"Products",item:`${siteConfig.url}/products`}]};return <><JsonLd data={breadcrumb}/><Hero eyebrow="Corefix Products" title="IT, Security & Infrastructure Products" description="Project-oriented product categories for CCTV, vehicle cameras, networking, perimeter security, fire alarms, PA systems and educational AV." compact/><section className="bg-core-950"><div className="mx-auto max-w-7xl px-3 py-12 sm:px-4 sm:py-20 lg:px-8"><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">{productCategories.map(p=><Link key={p.slug} href={`/products/${p.slug}`} className="flex min-h-[130px] flex-row gap-4 border border-white/10 bg-white/[.03] p-4 hover:border-yellow-400/50"><div className="h-10 w-10 shrink-0 border border-yellow-400/30 bg-yellow-400/10"/><div><h2 className="text-base font-bold sm:text-lg">{p.name}</h2><p className="mt-2 text-xs leading-5 text-white/55 sm:text-sm">{p.description}</p><span className="mt-3 inline-block text-xs font-bold text-yellow-400">Explore category →</span></div></Link>)}</div></div></section><CTASection/></>;}
